package com.epam.gym.entity;

public enum TrainingTypeEnum {
    STRENGTH_TRAINING,
    CARDIO,
    HIGH_INTENSITY_INTERVAL_TRAINING,
    CIRCUIT_TRAINING,
    BODYBUILDING,
    CROSSFIT,
    POWERLIFTING,
    OLYMPIC_WEIGHTLIFTING,
    FUNCTIONAL_TRAINING,
    CALISTHENICS,
    PILATES,
    YOGA,
    SPINNING,
    BOXING,
    SWIMMING,
    KETTLEBELL_TRAINING,
    AEROBICS,
    ZUMBA,
    REHABILITATION_TRAINING,
    FLEXIBILITY_TRAINING
}