name: gym-compose-app
# TODO: Send logs to grafana
# TODO: Setup the CI/CD pipeline
# TODO: Push the application to the cloud
services:
  postgres:
    image: postgres:latest
    ports:
      - target: 5432
        published: 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=gymDB
    networks:
      - gym-app-network
    volumes:
      - db-data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:4.0-management
    ports:
      - target: 15672
        published: 15672
    networks:
      - gym-app-network

  eureka:
    build: EurekaServer/
    ports:
      - target: 8761
        published: 8761
    environment:
      - EUREKA_INSTANCE_HOSTNAME=eureka
      - ZIPKIN_TRACING_ENDPOINT=http://zipkin:9411/api/v2/spans
    networks:
      - gym-app-network
    depends_on:
      - zipkin

  zipkin:
    image: openzipkin/zipkin:latest
    ports:
      - target: 9411
        published: 9411
    networks:
      - gym-app-network

  core-app:
    build: CoreMicroservice/
    ports:
      - target: 8080
        published: 8080
    environment:
      - RABBITMQ_HOST=rabbitmq
      - EUREKA_CLIENT_URL_DEFAULT_ZONE=http://eureka:8761/eureka
      - ZIPKIN_TRACING_ENDPOINT=http://zipkin:9411/api/v2/spans
      - POSTGRES_DATASOURCE_URL=postgres:5432/gymDB
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - gym-app-network
    depends_on:
      - rabbitmq
      - zipkin
      - eureka
      - postgres

  trainer-report-app:
    build: TrainerReportMicroservice/
    ports:
      - target: 8900
        published: 8900
    environment:
      - RABBITMQ_HOST=rabbitmq
      - EUREKA_CLIENT_URL_DEFAULT_ZONE=http://eureka:8761/eureka
      - ZIPKIN_TRACING_ENDPOINT=http://zipkin:9411/api/v2/spans
    networks:
      - gym-app-network
    depends_on:
      - rabbitmq
      - zipkin
      - core-app
      - eureka

  api-gateway:
    build: ApiGateway/
    environment:
      - EUREKA_CLIENT_URL_DEFAULT_ZONE=http://eureka:8761/eureka
      - ZIPKIN_TRACING_ENDPOINT=http://zipkin:9411/api/v2/spans
    ports:
      - target: 8888
        published: 8888
    networks:
      - gym-app-network
    depends_on:
      - core-app
      - trainer-report-app
      - zipkin
      - eureka

networks:
  gym-app-network:

volumes:
  db-data: